apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: model-service
spec:
  selector:
    app: model-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
