apiVersion: v1
kind: Service
metadata:
  name: message-service
  labels:
    app: message-service
spec:
  selector:
    app: message-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
