version: '3.9'
services:
  app1:
    container_name: app1
    image: arseny/prac5
    depends_on:
      check-db-started:
        condition: service_completed_successfully
  app2:
    container_name: app2
    image: arseny/prac5
    depends_on:
      check-db-started:
        condition: service_completed_successfully
  app3:
    container_name: app3
    image: arseny/prac5
    depends_on:
      check-db-started:
        condition: service_completed_successfully
  app4:
    container_name: app4
    image: arseny/prac5
    depends_on:
      check-db-started:
        condition: service_completed_successfully
  nginx:
    image: nginx:latest
    ports:
    - "80:8080"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      check-db-started:
        condition: service_completed_successfully
  db:
    image: postgres:17.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prac5
  check-db-started:
    image: jwilder/dockerize:0.6.1          
    depends_on:
        - db          
    command: 'dockerize -wait=tcp://db:5432 -timeout 30s'
